phrase:
  project_id: c82889bdf73013f4d77c664e5abdb1ec
  push:
    sources:
    - file: ./<locale_name>.html
      params:
        file_format: html
  pull:
    targets:
    - file: ./<locale_name>.html
      params:
        file_format: html
        format_options:
          # ID del documento HTML existente en el proyecto; obligatorio para exportar formatos basados en documento
          document_id: 90963b30ac605b5c7c3240b8548afcb7
