phrase:
  project_id: c82889bdf73013f4d77c664e5abdb1ec
  push:
    sources:
    - file: ./<locale_name>.html
      params:
        file_format: html
  pull:
    targets:
    - file: ./<locale_name>.html
      params:
        file_format: html
            format_options:
              document_id: "7968357ca3c34782464c85d478a73385"                             # ver nota